version: '3.8'
networks:
  test-network:

services:
  db:
    image: "mysql:5.7"
    restart: always
    container_name: db
    ports:
      - "${MYSQL_PORT_EXTERNAL}:3306"
    volumes:
      - mysql:/var/lib/mysql
      - ./docker/mysql/init/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
#      MYSQL_ALLOW_EMPTY_PASSWORD: true
      MYSQL_USER: test
      MYSQL_PASSWORD: test
#      MYSQL_DATABASE: trendyol_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - test-network

  app_trendyol_link:
    build: .
    container_name: app_trendyol_link
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_USERNAME=test
      - SPRING_DATASOURCE_PASSWORD=test
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/trendyol_db?characterEncoding=UTF8
    networks:
      - test-network
volumes:
  mysql:
    driver: local




